<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * The nginx map that turns a purged game's URL into a 410.
 *
 * The API has answered 410 for a tombstoned slug since the adult purge, and
 * none of it ever reached a crawler: the game page collapses any missing
 * record into `notFound()`, and Next has no way to answer anything but 404
 * from a page — there is no `gone()` beside `notFound()`, `forbidden()` and
 * `unauthorized()`. So Google has been told "maybe temporary" 60,981 times
 * about pages that are permanently gone, and keeps coming back to check: 131
 * of the 537 game pages it crawled in the first week of September were these.
 *
 * A 404 and a 410 are treated almost the same by Google, but not quite — a
 * 410 is dropped sooner and retried less. On a site whose crawl budget is the
 * binding constraint, "retried less" is the whole point.
 *
 * nginx answers them directly, which also stops 61,000 dead URLs being
 * rendered through Next to produce a 404 page nobody reads.
 *
 * Written to storage rather than to /etc: the application runs as www-data
 * and nginx's config is root's. deployment/sync_gone_games.sh installs it and
 * reloads, and only when the contents actually changed.
 */
class WriteGoneGamesMap extends Command
{
    protected $signature = 'games:gone-map {--path= : where to write, defaults to storage/app/nginx}';

    protected $description = 'Write the nginx map of purged game slugs that must answer 410';

    public function handle(): int
    {
        $dir = $this->option('path') ?: storage_path('app/nginx');

        if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
            $this->error("Could not create {$dir}");

            return self::FAILURE;
        }

        $file = rtrim($dir, '/').'/techplay-gone-games.conf';

        /*
         * The hash sizes are not optional at this scale.
         *
         * nginx builds a map into a hash table sized from these, and refuses
         * to start — not warns, refuses — when sixty thousand entries do not
         * fit. The bucket size has to be a multiple of the processor's cache
         * line; 128 is the safe value on x86-64.
         */
        $lines = [
            '# Generated by `php artisan games:gone-map`. Do not edit by hand.',
            '# Purged games, answered 410 so crawlers drop them rather than',
            '# returning to a 404 for months. See WriteGoneGamesMap.',
            '',
            'map_hash_max_size 262144;',
            'map_hash_bucket_size 128;',
            '',
            'map $uri $tp_game_gone {',
            '    default 0;',
        ];

        $count = 0;

        DB::table('game_tombstones')
            ->orderBy('slug')
            ->select('slug')
            ->chunk(5000, function ($rows) use (&$lines, &$count) {
                foreach ($rows as $row) {
                    $slug = (string) $row->slug;

                    // A slug with anything but the characters a URL path takes
                    // unescaped is skipped rather than quoted: nothing in the
                    // catalogue has ever had one, and a map entry that needs
                    // escaping is a map entry that can break the whole server.
                    if ($slug === '' || preg_match('/[^a-z0-9\-_.]/i', $slug)) {
                        continue;
                    }

                    $lines[] = '    /games/'.$slug.' 1;';
                    $count++;
                }
            });

        $lines[] = '}';
        $lines[] = '';

        file_put_contents($file, implode("\n", $lines));

        $this->info("  {$count} purged slugs written to {$file}");

        if ($count === 0) {
            $this->warn('  No tombstones found — the map allows everything through, which is the safe way to be wrong.');
        }

        return self::SUCCESS;
    }
}
