<?php

/**
 * ISO 3166-1 numeric codes, which is how IGDB gives a company's country.
 *
 * Resolved here rather than on the front so the mapping has one home: the API
 * hands out `{code, alpha2, name}` and nothing downstream has to know that 392
 * means Japan. A code that is not listed simply comes back without a name —
 * a studio missing its country line is a smaller wrong than a studio labelled
 * with somebody else's.
 *
 * 135 distinct codes appear across IGDB's 72,421 companies; the list below
 * covers those and the rest of the commonly used set.
 */
return [
    4 => ['AF', 'Afghanistan'],
    8 => ['AL', 'Albania'],
    12 => ['DZ', 'Algeria'],
    20 => ['AD', 'Andorra'],
    24 => ['AO', 'Angola'],
    31 => ['AZ', 'Azerbaijan'],
    32 => ['AR', 'Argentina'],
    36 => ['AU', 'Australia'],
    40 => ['AT', 'Austria'],
    44 => ['BS', 'Bahamas'],
    48 => ['BH', 'Bahrain'],
    50 => ['BD', 'Bangladesh'],
    51 => ['AM', 'Armenia'],
    52 => ['BB', 'Barbados'],
    56 => ['BE', 'Belgium'],
    60 => ['BM', 'Bermuda'],
    64 => ['BT', 'Bhutan'],
    68 => ['BO', 'Bolivia'],
    70 => ['BA', 'Bosnia and Herzegovina'],
    72 => ['BW', 'Botswana'],
    76 => ['BR', 'Brazil'],
    84 => ['BZ', 'Belize'],
    96 => ['BN', 'Brunei'],
    100 => ['BG', 'Bulgaria'],
    104 => ['MM', 'Myanmar'],
    112 => ['BY', 'Belarus'],
    116 => ['KH', 'Cambodia'],
    120 => ['CM', 'Cameroon'],
    124 => ['CA', 'Canada'],
    144 => ['LK', 'Sri Lanka'],
    152 => ['CL', 'Chile'],
    156 => ['CN', 'China'],
    170 => ['CO', 'Colombia'],
    188 => ['CR', 'Costa Rica'],
    191 => ['HR', 'Croatia'],
    192 => ['CU', 'Cuba'],
    196 => ['CY', 'Cyprus'],
    203 => ['CZ', 'Czechia'],
    208 => ['DK', 'Denmark'],
    214 => ['DO', 'Dominican Republic'],
    218 => ['EC', 'Ecuador'],
    222 => ['SV', 'El Salvador'],
    226 => ['GQ', 'Equatorial Guinea'],
    231 => ['ET', 'Ethiopia'],
    233 => ['EE', 'Estonia'],
    242 => ['FJ', 'Fiji'],
    246 => ['FI', 'Finland'],
    250 => ['FR', 'France'],
    268 => ['GE', 'Georgia'],
    276 => ['DE', 'Germany'],
    288 => ['GH', 'Ghana'],
    292 => ['GI', 'Gibraltar'],
    300 => ['GR', 'Greece'],
    320 => ['GT', 'Guatemala'],
    324 => ['GN', 'Guinea'],
    332 => ['HT', 'Haiti'],
    340 => ['HN', 'Honduras'],
    344 => ['HK', 'Hong Kong'],
    348 => ['HU', 'Hungary'],
    352 => ['IS', 'Iceland'],
    356 => ['IN', 'India'],
    360 => ['ID', 'Indonesia'],
    364 => ['IR', 'Iran'],
    368 => ['IQ', 'Iraq'],
    372 => ['IE', 'Ireland'],
    376 => ['IL', 'Israel'],
    380 => ['IT', 'Italy'],
    384 => ['CI', "Côte d'Ivoire"],
    388 => ['JM', 'Jamaica'],
    392 => ['JP', 'Japan'],
    398 => ['KZ', 'Kazakhstan'],
    400 => ['JO', 'Jordan'],
    404 => ['KE', 'Kenya'],
    408 => ['KP', 'North Korea'],
    410 => ['KR', 'South Korea'],
    414 => ['KW', 'Kuwait'],
    417 => ['KG', 'Kyrgyzstan'],
    418 => ['LA', 'Laos'],
    422 => ['LB', 'Lebanon'],
    428 => ['LV', 'Latvia'],
    438 => ['LI', 'Liechtenstein'],
    440 => ['LT', 'Lithuania'],
    442 => ['LU', 'Luxembourg'],
    446 => ['MO', 'Macao'],
    450 => ['MG', 'Madagascar'],
    458 => ['MY', 'Malaysia'],
    462 => ['MV', 'Maldives'],
    470 => ['MT', 'Malta'],
    480 => ['MU', 'Mauritius'],
    484 => ['MX', 'Mexico'],
    492 => ['MC', 'Monaco'],
    496 => ['MN', 'Mongolia'],
    498 => ['MD', 'Moldova'],
    499 => ['ME', 'Montenegro'],
    504 => ['MA', 'Morocco'],
    508 => ['MZ', 'Mozambique'],
    512 => ['OM', 'Oman'],
    516 => ['NA', 'Namibia'],
    524 => ['NP', 'Nepal'],
    528 => ['NL', 'Netherlands'],
    533 => ['AW', 'Aruba'],
    554 => ['NZ', 'New Zealand'],
    558 => ['NI', 'Nicaragua'],
    566 => ['NG', 'Nigeria'],
    578 => ['NO', 'Norway'],
    586 => ['PK', 'Pakistan'],
    591 => ['PA', 'Panama'],
    598 => ['PG', 'Papua New Guinea'],
    600 => ['PY', 'Paraguay'],
    604 => ['PE', 'Peru'],
    608 => ['PH', 'Philippines'],
    616 => ['PL', 'Poland'],
    620 => ['PT', 'Portugal'],
    630 => ['PR', 'Puerto Rico'],
    634 => ['QA', 'Qatar'],
    642 => ['RO', 'Romania'],
    643 => ['RU', 'Russia'],
    682 => ['SA', 'Saudi Arabia'],
    688 => ['RS', 'Serbia'],
    690 => ['SC', 'Seychelles'],
    702 => ['SG', 'Singapore'],
    703 => ['SK', 'Slovakia'],
    704 => ['VN', 'Vietnam'],
    705 => ['SI', 'Slovenia'],
    710 => ['ZA', 'South Africa'],
    716 => ['ZW', 'Zimbabwe'],
    724 => ['ES', 'Spain'],
    736 => ['SD', 'Sudan'],
    740 => ['SR', 'Suriname'],
    752 => ['SE', 'Sweden'],
    756 => ['CH', 'Switzerland'],
    760 => ['SY', 'Syria'],
    762 => ['TJ', 'Tajikistan'],
    764 => ['TH', 'Thailand'],
    780 => ['TT', 'Trinidad and Tobago'],
    784 => ['AE', 'United Arab Emirates'],
    788 => ['TN', 'Tunisia'],
    792 => ['TR', 'Türkiye'],
    795 => ['TM', 'Turkmenistan'],
    800 => ['UG', 'Uganda'],
    804 => ['UA', 'Ukraine'],
    807 => ['MK', 'North Macedonia'],
    818 => ['EG', 'Egypt'],
    826 => ['GB', 'United Kingdom'],
    834 => ['TZ', 'Tanzania'],
    840 => ['US', 'United States'],
    854 => ['BF', 'Burkina Faso'],
    858 => ['UY', 'Uruguay'],
    860 => ['UZ', 'Uzbekistan'],
    862 => ['VE', 'Venezuela'],
    887 => ['YE', 'Yemen'],
    894 => ['ZM', 'Zambia'],
];
