import type { Metadata } from "next";

/**
 * A search box is not a page, and its results are not pages either.
 *
 * /forum/search was answering `index, follow` with no canonical, so every
 * query anybody ran was a candidate for the index — an unbounded surface
 * generated by visitors. The site's other search, /search, has always been
 * noindex; this brings the forum's into line.
 *
 * The metadata lives in a layout because the page itself is a client
 * component and cannot export it.
 */
export const metadata: Metadata = {
    title: "Search the boards",
    description: "Search threads and posts across the TechPlay community forum.",
    robots: { index: false, follow: true },
};

export default function ForumSearchLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>;
}
