# Canonical per-week and per-day content for the Q4 2026 calendar.
import datetime as dt

GTA = dt.date(2026, 11, 19)

# Countdown facts: days-to-go -> (fact line, source tag). Only confirmed items (R17 ledger + hub data).
# Location names are used only after D-020 (gtadb provenance) is cleared, target 9 Oct -> days <= 40.
GTA_FACTS = {
52: ("19 November 2026, PS5 and Xbox Series X|S. That is the date, per Rockstar Newswire and the Xbox store page.", "R17 ledger"),
51: ("Lucia Caminos is one of the two protagonists.", "hub /gta6/characters/lucia-caminos"),
50: ("Jason Duval is the other protagonist.", "hub /gta6/characters"),
49: ("Standard edition price: $79.99.", "IGN 24 Jun 2026, R17"),
48: ("Ultimate Edition: $99.99.", "IGN 24 Jun 2026, R17"),
47: ("At launch, GTA VI is 'a single-player experience'. Online has no date.", "IGN 24 Jun 2026, R17"),
46: ("Rockstar calls the map 'a very big map', bigger than Red Dead Redemption 2's.", "IGN 27 Aug 2026, R17"),
45: ("No PC version at launch. Take-Two's CEO explained why in May.", "IGN 4 May 2026, R17"),
44: ("Airboats are back: the hub lists two, the Airboat 09 and the Airboat Fanboat.", "hub /gta6/vehicles"),
43: ("Cal Hampton is part of the confirmed supporting cast.", "hub /gta6/characters"),
42: ("Pre-orders opened 25 June. The pre-order bonus is the Vintage Vice City Pack.", "Rockstar Newswire, R17"),
41: ("The Speargun is on the confirmed weapon list.", "hub /gta6/weapons"),
40: ("Boobie Ike is part of the confirmed cast.", "hub /gta6/characters"),
39: ("Vice City International Airport has its own sign on the map. (Map facts cleared for use after the D-020 attribution check.)", "hub /gta6/map"),
38: ("36 weapons are on TechPlay's confirmed list so far, from the pistol to the grenade launcher.", "hub /gta6/weapons"),
37: ("121 vehicles are named so far, from the Blista Compact to the Blimp.", "hub /gta6/vehicles"),
36: ("Dre'Quan Priest is part of the confirmed cast.", "hub /gta6/characters"),
35: ("GTA VI: The Album, with Atlantic Records, comes out the same day as the game.", "Rockstar Newswire, R17"),
34: ("'An Extended Look' was captured on PS5, Rockstar says.", "Rockstar Newswire, R17"),
33: ("Raul Bautista is part of the confirmed cast.", "hub /gta6/characters"),
32: ("The Goodtime State – Vice City Collection costs about $400. The game is not included.", "Rockstar Newswire; GameSpot, Eurogamer; R17"),
31: ("The Palaestra Tower stands in Vice City.", "hub /gta6/map (post D-020)"),
30: ("Brian Heder is part of the confirmed cast.", "hub /gta6/characters"),
29: ("The Buzzard Attack Chopper is on the confirmed vehicle list.", "hub /gta6/vehicles"),
28: ("GTA VI was dated twice before: Fall 2025, then 26 May 2026. 19 Nov is the third date.", "Rockstar Newswire; Wikipedia; R17"),
27: ("Bae-Luxe is part of the confirmed cast.", "hub /gta6/characters"),
26: ("Golf is back: the Golf Club and Golf Ball are on the weapon list.", "hub /gta6/weapons"),
25: ("The Dodo seaplane is on the confirmed vehicle list.", "hub /gta6/vehicles"),
24: ("Jack Howitzer is part of the confirmed cast.", "hub /gta6/characters"),
23: ("13 years and 2 months: the gap between GTA V (17 Sep 2013) and GTA VI.", "C23 dataset; R17"),
22: ("There is a lighthouse on Catalan Key.", "hub /gta6/map (post D-020)"),
21: ("The Cheetah Classic is on the confirmed vehicle list.", "hub /gta6/vehicles"),
20: ("Jay Norris is part of the confirmed cast.", "hub /gta6/characters"),
19: ("The Pool Cue is on the confirmed weapon list.", "hub /gta6/weapons"),
18: ("Roxy is part of the confirmed cast.", "hub /gta6/characters"),
17: ("Waning Sands has an Evergreen Mall sign.", "hub /gta6/map (post D-020)"),
16: ("The Dominator GTX is on the confirmed vehicle list.", "hub /gta6/vehicles"),
15: ("Wyman is part of the confirmed cast.", "hub /gta6/characters"),
14: ("Tear gas is on the confirmed weapon list.", "hub /gta6/weapons"),
13: ("The Banshee returns on the confirmed vehicle list.", "hub /gta6/vehicles"),
12: ("12 characters are confirmed, including both protagonists.", "hub /gta6/characters"),
11: ("Launch platforms: PS5, Xbox Series X and Xbox Series S. Nothing else on day one.", "R17 ledger"),
10: ("1,058 map locations are pinned so far, with 211 still marked unconfirmed.", "hub /gta6/map (post D-020, with attribution)"),
9:  ("Pre-load: check the unlock time for your time zone on /gta6/release-time.", "C08 tool; times only once Rockstar/platforms publish them"),
8:  ("Standard $79.99 or Ultimate $99.99: what the difference is, per Rockstar's edition page.", "rs_ultimate-edition page, R17"),
7:  ("One week. Set a reminder so you get the unlock time for your region.", "C08"),
6:  ("Clear storage now. Download size will be posted here when the platforms list it.", "Fix It Friday 13 Nov"),
5:  ("GTA III is 25, Vice City 24, San Andreas 22. VI arrives in 5 days.", "On This Day data"),
4:  ("The Album with Atlantic Records drops on launch day, too.", "Rockstar Newswire"),
3:  ("Three days. The launch-night Discord event is scheduled: /events.", "C10"),
2:  ("Two days. Everything confirmed so far, in one page: /gta6/everything-we-know.", "C07"),
1:  ("Tomorrow. Unlock times for your time zone: /gta6/release-time.", "C08"),
0:  ("GTA VI is out today on PS5 and Xbox Series X|S.", "Rockstar"),
}

# Anniversaries with confidence (verify on the TechPlay game page before posting; skip if DB date differs).
OTD = {
"09-28": "Pokémon Red and Blue reached North America on 28 Sep 1998 (28 years). Genshin Impact launched on 28 Sep 2020.",
"09-29": "The Nintendo 64 launched in North America on 29 Sep 1996 (30 years). Tony Hawk's Pro Skater followed on 29 Sep 1999.",
"09-30": "",
"10-02": "Castlevania: Symphony of the Night reached North America on 2 Oct 1997. Ghost of Yōtei turns one today.",
"10-04": "Dark Souls launched in North America on 4 Oct 2011 (15 years).",
"10-05": "Assassin's Creed Mirage launched on 5 Oct 2023.",
"10-08": "Metroid Dread turns five. Silent Hill 2's remake turns two.",
"10-10": "The Orange Box (Half-Life 2: Episode Two, Portal, Team Fortress 2) launched on 10 Oct 2007. Battlefield 6 turns one.",
"10-11": "Metaphor: ReFantazio turns two. Its Switch 2 edition lands 12 Nov.",
"10-13": "Uncharted 2: Among Thieves launched on 13 Oct 2009.",
"10-15": "Disco Elysium launched on 15 Oct 2019. Pokémon Gold and Silver reached North America on 15 Oct 2000.",
"10-16": "Pokémon Legends: Z-A turns one.",
"10-18": "Batman: Arkham City launched on 18 Oct 2011 (15 years).",
"10-19": "Fallout: New Vegas launched on 19 Oct 2010.",
"10-20": "Marvel's Spider-Man 2 and Super Mario Bros. Wonder both launched on 20 Oct 2023.",
"10-22": "Grand Theft Auto III launched on 22 Oct 2001: 25 years ago today, 28 days before GTA VI.",
"10-23": "Lethal Company appeared on Steam on 23 Oct 2023. Today it shares a birthday with Modern Warfare 4.",
"10-25": "Call of Duty: Black Ops 6 turns two.",
"10-26": "Red Dead Redemption 2 launched on 26 Oct 2018. GTA: San Andreas reached North America on 26 Oct 2004.",
"10-27": "Super Mario Odyssey (2017) and Alan Wake 2 (2023) share today's date.",
"10-28": "Fallout 3 (2008) and Titanfall 2 (2016) both launched on 28 Oct.",
"10-29": "GTA: Vice City reached North America on 29 Oct 2002, 24 years before VI brings Vice City back.",
"10-30": "Arc Raiders turns one.",
"10-31": "Luigi's Mansion 3 launched on Halloween 2019.",
"11-03": "Dragon Age: Origins launched on 3 Nov 2009.",
"11-05": "Call of Duty 4: Modern Warfare launched on 5 Nov 2007, the series MW4 continues.",
"11-08": "Death Stranding launched on 8 Nov 2019.",
"11-09": "Halo 2 (2004) and God of War Ragnarök (2022) share today's date.",
"11-10": "Fallout 4 (2015) and Xbox Series X|S (2020) both launched on 10 Nov.",
"11-11": "The Elder Scrolls V: Skyrim launched on 11 Nov 2011 (15 years).",
"11-12": "PS5 launched in North America on 12 Nov 2020.",
"11-13": "Metal Gear Solid 2 reached North America on 13 Nov 2001 (25 years).",
"11-14": "Call of Duty: Black Ops 7 turns one.",
"11-15": "Halo: Combat Evolved and the original Xbox launched on 15 Nov 2001 (25 years).",
"11-16": "Half-Life 2 launched on 16 Nov 2004.",
"11-17": "Metroid Prime (2002) and Left 4 Dead (2008) share today's date.",
"11-18": "Minecraft 1.0 released on 18 Nov 2011 (15 years).",
"11-19": "Half-Life (1998) and the Wii in North America (2006) share today's date with GTA VI.",
"11-20": "S.T.A.L.K.E.R. 2 turns two. Mass Effect launched on 20 Nov 2007.",
"11-21": "The Nintendo DS launched in North America on 21 Nov 2004.",
"11-22": "The Xbox 360 launched on 22 Nov 2005; the Xbox One on 22 Nov 2013.",
"11-23": "World of Warcraft launched on 23 Nov 2004 (22 years).",
"11-24": "Sonic the Hedgehog 2 launched on 'Sonic 2sday', 24 Nov 1992.",
"12-03": "Super Smash Bros. Melee reached North America on 3 Dec 2001 (25 years).",
"12-04": "Metroid Prime 4 turns one.",
"12-05": "The first GTA VI trailer went up on 5 Dec 2023.",
"12-08": "Halo Infinite's campaign launched on 8 Dec 2021.",
"12-09": "Indiana Jones and the Great Circle turns two.",
"12-10": "DOOM (1993) and Cyberpunk 2077 (2020) both launched on 10 Dec, also The Game Awards night.",
"12-17": "Final Fantasy X reached North America on 17 Dec 2001 (25 years).",
}
OTD_RULE = "Buffy posts the top-rated result from /api/v1/games/on-this-day at 09:00 CET; SC swaps in a better-known title from the same list if one exists"

# Weekly content keyed by Monday.
W = {}
def week(mon, **kw): W[mon] = kw

week("2026-09-28", n=40, theme="Trust reset, systems on",
 otw="Minecraft Dungeons II (29 Sep), Ghost of Yōtei Complete Edition with the Most Wanted mode (1 Oct, reported), Ace Combat 8: Wings of Theve (2 Oct), Steam Autumn Sale opens 1 Oct",
 wayp="What are you playing this week, and is anything on your wishlist waiting for the Autumn Sale on 1 Oct?",
 wcip_tue="Minecraft Dungeons II: platforms, price and cross-play, per Mojang", verdict=None,
 movers="Steam Movers #1: the week's biggest climbers in Steam's most-played chart, with a methodology line",
 ready="Patch 12.1.5 is predicted for around 6 Oct but not announced. Run your character now for a 'before' snapshot.",
 num_tue="13 years, 2 months: the gap between GTA V (17 Sep 2013) and GTA VI (19 Nov 2026).",
 poll="Do you still buy games on disc? (Mostly / Sometimes / Collector's editions only / Never)",
 wit="Is Xbox Game Pass Ultimate worth it in 2026? Price from Xbox's page on the day, plus what's coming in October",
 studio="Studio Watch: Xbox restructuring this week, what's confirmed and which studios it touches",
 hg="Chants of Sennaar (2023): a puzzle game about learning languages that nobody around you speaks",
 num_thu="212.3 million Americans play video games every week (ESA Essential Facts 2026).",
 ledger="Ledger launch: 18 claims, each marked Confirmed, Reported or Rumour, with source and date",
 fif="Shader compilation stutter: what it is, why it happens on PC, and the three settings you can actually change",
 sf_subj="The Save File #1: What's out, what's on sale, and 52 days to Vice City",
 io="Gears of War in order: every game from 2006 to E-Day, and which ones you can skip",
 wcip_sat="Gears of War: E-Day on 6 Oct: Xbox, PC, and whether it's on Game Pass day one (verify with Xbox)",
 num_sat="333,000+ games in the TechPlay catalogue, and every one can go on your shelf (re-count on the day).",
 gl="Games like Gears of War: 8 cover shooters with a real campaign",
 club="Game Club October pick announced: Control Resonant (discussion night Thu 29 Oct)")

week("2026-10-05", n=41, theme="Gears launch, Autumn Sale end, Release Congestion data",
 otw="Gears of War: E-Day (6 Oct), WoW patch 12.1.5 (predicted ~6 Oct), Steam Autumn Sale ends 8 Oct, Dragon's Dogma 2: Dark Arisen incl. Switch 2 (9 Oct)",
 wayp="Gears, Dragon's Dogma or a sale pick: what's in rotation this week?",
 wcip_tue="Gears of War: E-Day: every way to play it on launch day",
 verdict=("thu","Verdict: Gears of War: E-Day"),
 movers="Steam Movers #2: where Gears of War: E-Day enters Steam's most-played chart",
 ready="If 12.1.5 is live, run the Analyzer again and compare it with last week's snapshot.",
 num_tue="Release Congestion teaser: the number of notable games dated between 19 Oct and 23 Nov (from the C20 query, run on the day).",
 poll="Is 2026's Q4 too crowded? Which game are you pushing to 2027?",
 wit="Is Cyberpunk 2077 worth playing in 2026? The Verdict on the current version",
 studio="Studio Watch: tracker prep, every closure logged since 1 Jan with a source link (goes public 14 Oct)",
 hg="Citizen Sleeper (2022): a dice-driven RPG about surviving on a space station",
 num_thu="Release Congestion Index 2026: headline figure from the study published Wed 7 Oct.",
 ledger="Ledger update: add anything Rockstar or Take-Two said this week; move nothing to Confirmed without a first-party source",
 fif="Windows 11 settings that matter for games: Game Mode, hardware-accelerated GPU scheduling, Memory Integrity (VBS)",
 sf_subj="The Save File #2: Gears is out, the sale ends Thursday, and Q4 has a traffic jam",
 io="Castlevania in order: from the NES to Belmont's Curse (15 Oct)",
 wcip_sat="Dragon's Dogma 2 on Switch 2: what Dark Arisen adds and which version to buy",
 num_sat="4,358 demos took part in June 2026's Steam Next Fest (GameDiscoverCo). October's fest starts 19 Oct.",
 gl="Games like Dragon's Dogma 2: 7 RPGs with companions that actually matter")

week("2026-10-12", n=42, theme="PC Fix Hub, Studios Closed tracker, GTA release-time tool, MW4 early access",
 otw="Planet Zoo 2 (13 Oct), Enshrouded 1.0 + Castlevania: Belmont's Curse + Crimson Desert DLC (15 Oct), MW4 campaign early access (16 Oct), Steam Cooking Fest 12–19 Oct, LoL Worlds from 15 Oct",
 wayp="Enshrouded 1.0, Planet Zoo 2 or an early MW4 campaign run: what's on this week?",
 wcip_tue="Modern Warfare 4: platforms incl. Switch 2, early access for digital pre-orders on 16 Oct, per Activision",
 verdict=("mon","Verdict: Minecraft Dungeons II"),
 movers="Steam Movers #3: Planet Zoo 2 and Enshrouded 1.0 entries",
 ready="Readiness Check: three things the Analyzer flags most often and what fixes each (from the Analyzer's output fields)",
 num_tue="The number of studios closed in 2026 so far, counted in the new tracker (C22, live Wed 14 Oct).",
 poll="Call of Duty on Switch 2: would you play MW4 on a handheld?",
 wit="Is No Man's Sky worth playing in 2026?",
 studio="Studios Closed in 2026 tracker goes live (C22): every closure with date, owner, headcount if reported, and source",
 hg="Chained Echoes (2022): a 16-bit style JRPG that respects your time",
 num_thu="Steam Next Fest runs 19–26 Oct. The press preview opened on 8 Oct (Steamworks schedule).",
 ledger="Ledger update + link the release-time tool from every GTA 6 page",
 fif="Secure Boot and TPM 2.0: how to check and switch them on for anti-cheat games like Call of Duty",
 sf_subj="The Save File #3: MW4 early access, a fix hub for PC players, and what closed this year",
 io="Call of Duty: Modern Warfare in order, 2007 to MW4",
 wcip_sat="Enshrouded 1.0: where to play and whether early-access saves carry over (per Keen Games)",
 num_sat="7 days until Steam Next Fest. TechPlay tracks 3 demos a day in the Next Fest Diary.",
 gl="Games like Call of Duty: 8 shooters with campaigns worth finishing")

week("2026-10-19", n=43, theme="Steam Next Fest + MW4 launch + off-site alerts go live",
 otw="Steam Next Fest (19–26 Oct), PS Plus Extra/Premium October drop (20 Oct), FF Resonance + Switch Sports Resort + Once Human: Isles of Abyss (22 Oct), Call of Duty: Modern Warfare 4 (23 Oct)",
 wayp="Which Next Fest demos have you tried? Drop the names; we'll add the best to the diary.",
 wcip_tue="PS Plus Extra and Premium, October: the new games and where else each one is playable",
 verdict=("mon","Verdict: Ace Combat 8: Wings of Theve"),
 movers="Steam Movers #4: Next Fest demos in the most-played chart",
 ready="Readiness Check: which stat to fix first if your score dropped after 12.1.5",
 num_tue="Next Fest day 2: the three most-played demos on Steam right now.",
 poll="Best Next Fest demo so far? (four options from the diary, plus 'other')",
 wit="Is a PS5 Pro worth buying before GTA VI? What's confirmed about performance (and what's only reported)",
 studio="Studio Watch: tracker update, plus which Next Fest demos come from studios in our Balkan census",
 hg="Signalis (2022): survival horror in the Resident Evil mould, made by two people",
 num_thu="121 vehicles in the GTA VI hub, now with classes (C12 vehicle guide, 21 Oct).",
 ledger="Ledger update: the vehicle guide's sourcing rules added to the method note",
 fif="Download stuck on launch day: fixes for Battle.net, Steam, PS5 and Xbox",
 sf_subj="The Save File #4: Next Fest picks, MW4 is out, and your games now email you",
 io="Yakuza / Like a Dragon in order, before Stranger Than Heaven (15 Jan)",
 wcip_sat="Minecraft Bedrock on Switch 2 (27 Oct): cross-play and the upgrade path",
 num_sat="MW4's Steam concurrent-player peak on launch day (Steam API, pulled Sat morning).",
 gl="Games like Silent Hill: 8 horror games for Scream Fest")

week("2026-10-26", n=44, theme="Halloween, Switch 2 hub, Balkan Game Dev Census, first personalised email",
 otw="Steam Scream Fest (26 Oct–2 Nov), Minecraft Bedrock on Switch 2 (27 Oct), Phantom Blade Zero (29 Oct), Halloween events, Season 2 'Overdrive' on TechPlay (1 Nov)",
 wayp="Horror pick, Phantom Blade Zero or still on MW4?",
 wcip_tue="Minecraft on Switch 2: Bedrock edition, cross-play, and what happens to your Switch 1 purchase (per Mojang)",
 verdict=("mon","Verdict: Call of Duty: Modern Warfare 4 (campaign)"),
 movers="Steam Movers #5: Scream Fest discounts in the chart",
 ready="Readiness Check: WoW: Forever arrives 4 Nov. What it is and whether the Analyzer covers it (answer from the product, not a guess)",
 num_tue="Balkan census teaser: the number of studios TechPlay lists in Bosnia and Herzegovina (query /studios/country/ba on the day).",
 poll="Scariest game you've actually finished?",
 wit="Is Red Dead Redemption 2 worth playing before GTA VI?",
 studio="World Atlas of Game Studios + Balkan Game Dev Census published (C21)",
 hg="Crow Country (2024): a PS1-style horror mystery set in a closed theme park",
 num_thu="Balkan Game Dev Census headline number (from C21, re-run by a second person).",
 ledger="Ledger update + 'what we still don't know' section refreshed",
 fif="Steam Deck and handheld PCs: the battery settings that make a real difference",
 sf_subj="The Save File #5: Halloween picks, a census of Balkan studios, and 24 days to Vice City",
 io="Resident Evil in order: main games, remakes and where to start",
 wcip_sat="Phantom Blade Zero: PS5 and PC. Is there an Xbox version? (per S-GAME)",
 num_sat="Horror games released in 2026 so far, by TechPlay's genre tags (query on the day).",
 gl="Games like Black Myth: Wukong: action games in the Phantom Blade Zero mould")

week("2026-11-02", n=45, theme="Steam hub, WoW: Forever, Sequel Gap data, paid test starts (if gated)",
 otw="WoW: Forever (4 Nov), Stellar Blade Complete Edition + Guardians of the Galaxy + Edge of Memories (5 Nov), PS Plus renewal price change (6 Nov, verify with Sony), IEM Beijing (2–8 Nov)",
 wayp="Anyone going back to Azeroth for WoW: Forever?",
 wcip_tue="Stellar Blade Complete Edition and the 5 Nov ports: which platforms get what",
 verdict=("mon","Verdict: Phantom Blade Zero"),
 movers="Steam Movers #6: post-Halloween chart",
 ready="Readiness Check: WoW: Forever launch day. Which version your character data comes from",
 num_tue="13 years: the longest gap between two mainline GTA games (C23 teaser).",
 poll="Longest you've ever waited for a sequel?",
 wit="Which WoW should you play in 2026: retail, Classic or Forever?",
 studio="Sequel Gap Inflation published (C23): why GTA VI took 13 years, in data",
 hg="Heaven's Vault (2019): archaeology, a robot companion and a dead language to decode",
 num_thu="The median gap between sequels in TechPlay's series table, 2000s vs 2020s (C23, re-run on the day).",
 ledger="Ledger update: anything new on pre-load, file size or launch times",
 fif="DirectX 12 'device removed' and 'device hung' errors: what they mean and fixes that work",
 sf_subj="The Save File #6: Why GTA VI took 13 years, and which WoW to play now",
 io="World of Warcraft expansions in order, Vanilla to Midnight",
 wcip_sat="WoW: Forever: what you need to play it and what it costs (per Blizzard)",
 num_sat="57,630 studios in TechPlay's atlas (re-count on the day).",
 gl="Games like World of Warcraft: MMOs worth starting in 2026")

week("2026-11-09", n=46, theme="GTA VI final run-up, MMO hub, $80 tracker, web push, YouTube pilot",
 otw="Pikmin 4 Switch 2 Edition + Metaphor: ReFantazio Switch 2 (12 Nov), LoL Worlds final (14 Nov), GTA VI in 10 days",
 wayp="Last week before GTA VI: what are you finishing first?",
 wcip_tue="Metaphor: ReFantazio on Switch 2: what changes from the original",
 verdict=("mon","Verdict: Enshrouded 1.0"),
 movers="Steam Movers #7",
 ready="Readiness Check + /mmo hub is live (10 Nov)",
 num_tue="The number of 2026 games priced at $79.99 or more (the $80 tracker, C24, published Wed 11 Nov).",
 poll="GTA VI: Standard ($79.99) or Ultimate ($99.99)?",
 wit="Is the $99.99 GTA VI Ultimate Edition worth it? What's in it, per Rockstar",
 studio="The $80 Tracker published (C24)",
 hg="Jusant (2023): a climbing game with no combat and a lot of quiet",
 num_thu="$79.99: GTA VI's standard price, and where it sits in the $80 tracker.",
 ledger="Ledger update: final pre-launch pass, every open rumour marked",
 fif="PS5 and Xbox storage: freeing space before GTA VI pre-loads (file size once platforms list it)",
 sf_subj="The Save File #7: 7 days. Everything you need before GTA VI",
 io="Grand Theft Auto in order: every mainline game, 1997 to VI",
 wcip_sat="GTA VI on 19 Nov: PS5 and Xbox Series X|S only. No PC, no Switch 2, no Online at launch",
 num_sat="5 days to GTA VI.",
 gl="Games like GTA for PC players (no PC version at launch)")

week("2026-11-16", n=47, theme="GTA VI launch week",
 otw="GTA VI (19 Nov), GTA VI: The Album (19 Nov), GTA VI DualSense (19 Nov, reported), Steam Auto-Battler RPG Fest (16–23 Nov)",
 wayp="Launch week. Who's taking the day off?",
 wcip_tue="GTA VI: PS5 vs Xbox Series X vs Series S, what's confirmed about each version",
 verdict=("mon","Verdict: Metaphor: ReFantazio on Switch 2"),
 movers="Steam Movers #8: what PC players did in GTA VI week",
 ready="Readiness Check (light week)",
 num_tue="3 days to GTA VI.",
 poll="Launch night: are you playing at unlock or next morning?",
 wit=None,
 studio="Studio Watch: skipped unless news breaks",
 hg="Sleeping Dogs (2012): for PC players without GTA VI tonight",
 num_thu="12 characters, 36 weapons, 121 vehicles, 1,058 pinned locations: the hub before launch. From today the game itself checks our work.",
 ledger="Launch-day ledger: everything confirmed by the game itself replaces pre-release claims",
 fif="GTA VI download and pre-load troubleshooting on PS5 and Xbox (only confirmed issues)",
 sf_subj="The Save File #8: GTA VI week, part two",
 io="Warhammer 40,000: Dawn of War in order, before Dawn of War IV (3 Dec)",
 wcip_sat="Auto-battlers on Steam: the fest picks and where each one runs",
 num_sat="GTA VI day 3: map locations checked off by TechPlay members in the progress tracker (C11, live count).",
 gl="Open-world crime games to play while GTA Online waits (Online has no date)")

week("2026-11-23", n=48, theme="Black Friday with wishlist price alerts",
 otw="US Thanksgiving (26 Nov), Black Friday (27 Nov), PGL CS2 Major (25 Nov–13 Dec), GTA VI week two",
 wayp="GTA VI week two, or saving it for the holidays?",
 wcip_tue="GTA VI edition upgrade: Standard to Ultimate, if Rockstar offers one",
 verdict=("mon","Verdict in progress: GTA VI, first 20 hours"),
 movers="Steam Movers #9",
 ready="Readiness Check",
 num_tue="Best-value games of 2026: hours of play per dollar (C25, published Mon 23 Nov).",
 poll="What are you actually buying on Black Friday?",
 wit="Is a Steam Deck worth it on Black Friday 2026?",
 studio="Studio Watch: tracker update",
 hg="A Short Hike (2019): a two-hour game for a long weekend",
 num_thu="Games on your wishlists that hit a price low this week (aggregate from price alerts, if D-027 shipped).",
 ledger="Ledger: post-launch patch notes and GTA Online status",
 fif="Controller not detected on PC: Steam Input and driver fixes",
 sf_subj="The Save File #9: Black Friday, filtered by what you actually want",
 io="Monster Hunter in order: which games matter before Wilds on Switch 2",
 wcip_sat="Monster Hunter Wilds on Switch 2 (4 Dec): cross-play and save transfer, per Capcom",
 num_sat="Wishlisted games under $20 this weekend, from the deal radar.",
 gl="Games like Monster Hunter")

week("2026-11-30", n=49, theme="Cyber Monday, Community Awards open, gift guide",
 otw="Cyber Monday (30 Nov), Dawn of War IV + Dragon Quest Monsters: The Withered World + Xenoblade 3 Switch 2 + Rayman Legends Retold (3 Dec), Monster Hunter Wilds Switch 2 (4 Dec)",
 wayp="Dawn of War IV, Monster Hunter on Switch 2, or GTA VI still?",
 wcip_tue="Xenoblade Chronicles 3 Switch 2 Edition: upgrade or new purchase?",
 verdict=("mon","Verdict: Grand Theft Auto VI"),
 movers="Steam Movers #10",
 ready="Readiness Check",
 num_tue="Community Awards: the number of nominations in the first 24 hours (live count).",
 poll="Community Awards: your Game of the Year?",
 wit="Is Switch 2 worth buying for Christmas 2026?",
 studio="Studio Watch: tracker update",
 hg="Pentiment (2022): a murder mystery in a 16th-century Bavarian town",
 num_thu="3 years since the first GTA VI trailer (5 Dec 2023).",
 ledger="Ledger: Online and PC watch",
 fif="Switch 2 microSD Express cards: what works and what doesn't",
 sf_subj="The Save File #10: Gift ideas from real wishlists, and the Community Awards are open",
 io="Persona in order, before Persona 4 Revival (18 Feb)",
 wcip_sat="Dawn of War IV: PC only, and what your PC needs",
 num_sat="7 days to The Game Awards.",
 gl="Games like Persona")

week("2026-12-07", n=50, theme="The Game Awards week",
 otw="The Game Awards (10 Dec), Professor Layton and the New World of Steam + Attack on Titan 3 (10 Dec), Path of Exile 2 1.0 (11 Dec, reported)",
 wayp="TGA predictions thread: what wins GOTY?",
 wcip_tue="Path of Exile 2 1.0: platforms and whether early-access characters carry over (per Grinding Gear)",
 verdict=("mon","Verdict: Warhammer 40,000: Dawn of War IV"),
 movers="Steam Movers #11",
 ready="Readiness Check",
 num_tue="Achievement difficulty by genre, 500 Steam games (C26, published Tue 8 Dec).",
 poll="Game of the Year at The Game Awards: who wins?",
 wit="Is Monster Hunter Wilds on Switch 2 worth it?",
 studio="Studio Watch: tracker update",
 hg="Cocoon (2023): worlds inside worlds, from a Limbo and Inside designer",
 num_thu="TGA night: the number of new game reveals (live count).",
 ledger="Ledger: anything shown at TGA",
 fif="Path of Exile 2 at 1.0: clearing the shader cache on Nvidia, AMD and Intel",
 sf_subj="The Save File #11: Every TGA reveal worth adding to your list",
 io="Final Fantasy VII in order, before Revelation (8 Apr 2027)",
 wcip_sat="Everything announced at TGA: platforms and dates, one table",
 num_sat="Your 2026 in Games opens 14 Dec.",
 gl="Games like Diablo and Path of Exile")

week("2026-12-14", n=51, theme="Your 2026 in Games + Steam Winter Sale",
 otw="Your 2026 in Games opens (14 Dec), Steam Winter Sale (17 Dec–4 Jan), Community Awards results (20 Dec)",
 wayp="What's on your Winter Sale list?",
 wcip_tue="Game Pass and PS Plus: what joins in the second half of December",
 verdict=("mon","Verdict: Monster Hunter Wilds on Switch 2"),
 movers="Steam Movers #12: Winter Sale",
 ready="Readiness Check",
 num_tue="Year in Review: the number of recaps generated in the first 24 hours (live).",
 poll="Community Awards final round",
 wit="Steam Deck LCD or OLED in the Winter Sale?",
 studio="Studio Watch: tracker update",
 hg="Norco (2022): a point-and-click about industrial Louisiana",
 num_thu="The most-wishlisted game among TechPlay members that's discounted in the Winter Sale.",
 ledger="Ledger: monthly pass",
 fif="New GPU for Christmas: a clean driver install (DDU) and the first checks",
 sf_subj="The Save File #12: Winter Sale picks from your wishlists",
 io="Metroid in order, before Metroid Ravenous (28 Jan)",
 wcip_sat="Winter Sale: best discounts on Steam Deck Verified games",
 num_sat="Community Awards: the winning margin in the closest category.",
 gl="Cozy games like Stardew Valley")

week("2026-12-21", n=52, theme="Holidays, most-anticipated 2027",
 otw="Christmas (25 Dec), Steam Winter Sale continues, 2027 Most Anticipated list (C70)",
 wayp="Holiday week: what are you playing?",
 wcip_tue="New console at Christmas: which games to download first on PS5, Xbox, Switch 2",
 verdict=("mon","Verdict: Path of Exile 2 1.0"),
 movers="Steam Movers #13",
 ready="Readiness Check",
 num_tue="The number of 2027 games already dated in TechPlay's calendar (query on the day).",
 poll="Best game you played in 2026 that didn't come out in 2026?",
 wit="PS Plus or Game Pass for a new console owner?",
 studio="Studio Watch: skipped",
 hg="Venba (2023): a cooking game about a family's migration",
 num_thu=None,
 ledger="Ledger: skipped",
 fif="New console setup: first-hour settings for PS5, Xbox and Switch 2 (published Wed 23 Dec)",
 sf_subj="The Save File holiday edition: What to play over the break",
 io="Fable in order, before Fable (23 Feb 2027)",
 wcip_sat="Fable (23 Feb 2027): Xbox, PC, PS5 and Game Pass",
 num_sat="Days until Fable: 59.",
 gl="Games like Baldur's Gate 3")

week("2026-12-28", n=53, theme="Year-end, 2027 bridge",
 otw="Steam Winter Sale final week (ends 4 Jan), CES and FFXIV: Evercold in January",
 wayp="Last check-in of 2026: what are you finishing before 1 Jan?",
 wcip_tue="Q1 2027 releases: platforms and dates in one table",
 verdict=("mon","Every Verdict of 2026 in one table"),
 movers="Steam Movers: year-end",
 ready="Readiness Check: The Last Titan is dated '2027' only; what that means for your character plan",
 num_tue="Studios closed in 2026: the final count (C22).",
 poll="Most anticipated game of 2027?",
 wit=None,
 studio="Studios Closed in 2026: final count",
 hg="1000xRESIST (2024): a science-fiction story about memory",
 num_thu=None, ledger=None, fif=None, sf_subj=None, io=None, wcip_sat=None, num_sat=None, gl=None)
